server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.206.66
    username: leyou
    password: 123321
    virtual-host: /leyou
  redis:
    host: 192.168.58.101
ly:
  sms:
    accessKeyId: JWffwFJIwada # 你自己的accessKeyId
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: J商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称